# Generated by Django 5.1.5 on 2026-06-04 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0002_class_created_at_alter_class_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AssignedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True, verbose_name='Course Code/ID')),
                ('course_name', models.CharField(max_length=255)),
                ('session', models.CharField(help_text='e.g., 2023-24, Spring-2026', max_length=50)),
                ('semester', models.IntegerField(help_text='Enter semester number (1-8)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assigned Course',
                'verbose_name_plural': 'Assigned Courses',
            },
        ),
    ]
