# Generated by Django 5.1.5 on 2026-06-04 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('teacher_dashboard', '0003_alter_class_teacher_assignedcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_courses', to='authentication.user'),
        ),
        migrations.AlterField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='authentication.user'),
        ),
    ]
