# Generated by Django 5.1.5 on 2026-06-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('teacher_dashboard', '0004_alter_assignedcourse_teacher_alter_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.FloatField(default=0.0)),
                ('class_test_1', models.FloatField(default=0.0)),
                ('class_test_2', models.FloatField(default=0.0)),
                ('attendance_marks', models.FloatField(default=0.0)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_marks', to='teacher_dashboard.assignedcourse')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='my_marks', to='authentication.user')),
            ],
            options={
                'verbose_name': 'Student Mark',
                'verbose_name_plural': 'Student Marks',
                'unique_together': {('assigned_course', 'student')},
            },
        ),
    ]
