# Generated by Django 5.1.5 on 2026-07-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0005_studentmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourse',
            name='course_id',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Course Code/ID'),
        ),
    ]
