# Generated by Django 5.1.5 on 2026-07-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0006_alter_assignedcourse_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='course_code',
            field=models.CharField(max_length=50),
        ),
    ]
