# Generated by Django 5.1.5 on 2026-07-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0007_alter_class_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='session',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
