# Generated by Django 5.1.5 on 2026-05-19 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('teacher_dashboard', '0002_class_created_at_alter_class_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='attendance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attended_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dashboard.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
    ]
