# Generated by Django 5.1.5 on 2026-05-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='image',
        ),
        migrations.AddField(
            model_name='attendance',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
